#!/usr/bin/env python3
# Generated by tutor-handouts. Linter for the rule files themselves (NOT the runtime banned-phrase scan).
#
# Verifies:
#   (a) Every .md rule file under content-rules/ has a `# Rules` H1 heading and at least one numbered list
#   (b) Every rule ID referenced by quality-checklist.md exists in exactly one of the content-rules/*.md files
#   (c) Every invariant ID INV-1..INV-8 appears at least once across the rule files (excluding the checklist)
#
# Usage:
#   python check-content-rules.py <content-rules-dir>
# Exit codes: 0 = OK, 1 = violations

from __future__ import annotations

import re
import sys
from pathlib import Path


def main() -> int:
    if len(sys.argv) != 2:
        print("usage: check-content-rules.py <content-rules-dir>", file=sys.stderr)
        return 2

    cr_dir = Path(sys.argv[1]).resolve()
    if not cr_dir.is_dir():
        print(f"error: not a directory: {cr_dir}", file=sys.stderr)
        return 2

    # The quality-checklist.md sits one level above content-rules/
    refs_dir = cr_dir.parent
    qc_path = refs_dir / "quality-checklist.md"
    if not qc_path.exists():
        print(f"error: cannot find {qc_path}", file=sys.stderr)
        return 2

    files = sorted(cr_dir.glob("*.md"))
    if not files:
        print(f"error: no .md files under {cr_dir}", file=sys.stderr)
        return 2

    violations: list[str] = []

    # (a) Each rule file has `# Rules` H1 heading and ≥1 numbered list
    for f in files:
        text = f.read_text()
        if not re.search(r"^# Rules", text, re.M):
            violations.append(f"{f.name}: missing '# Rules' H1 heading")
        if not re.search(r"^\d+\.\s|^\s*\d+\.\s", text, re.M):
            violations.append(f"{f.name}: no numbered list found")

    # (b) Every rule ID referenced from quality-checklist exists exactly once across rule files
    qc_text = qc_path.read_text()
    # Rule references in checklist look like: HCR-1, ECR-12, RR-3, INV-5
    referenced = set(re.findall(r"\b(HCR-\d+|ECR-\d+|RR-\d+)\b", qc_text))

    defined: dict[str, list[str]] = {}
    for f in files:
        text = f.read_text()
        # Definitions look like: **HCR-1 (...)**, **ECR-12 ...**, **RR-3 ...**
        for m in re.finditer(r"\*\*(HCR-\d+|ECR-\d+|RR-\d+)(?:\s|\)|\*)", text):
            rule_id = m.group(1)
            defined.setdefault(rule_id, []).append(f.name)

    orphans = sorted(r for r in referenced if r not in defined)
    duplicates = sorted(r for r, files_with_r in defined.items() if len(files_with_r) > 1)

    if orphans:
        violations.append(f"orphan rule references (in checklist but not defined): {orphans}")
    if duplicates:
        violations.append(f"duplicate rule definitions: {duplicates}")

    # (c) Every invariant INV-1..INV-8 appears at least once across the broader rules system
    # (content-rules/ + style-guide.md + quality-checklist.md). All three are pedagogy contracts.
    rules_corpus_files = list(files) + [
        p for p in (refs_dir / "style-guide.md", refs_dir / "quality-checklist.md") if p.exists()
    ]
    rule_corpus = "\n".join(f.read_text() for f in rules_corpus_files)
    inv_total = 8
    covered = sorted(
        int(m.group(1))
        for m in re.finditer(r"\bINV-(\d+)\b", rule_corpus)
    )
    covered_set = set(covered)
    missing = sorted(set(range(1, inv_total + 1)) - covered_set)
    inv_covered_count = len(covered_set & set(range(1, inv_total + 1)))
    if missing:
        violations.append(f"invariants not referenced in rule files: INV-{missing}")

    if violations:
        print("FAIL")
        for v in violations:
            print(f"  - {v}")
        return 1

    print(
        f"OK: {len(files)} files scanned, "
        f"{len(orphans)} orphans, "
        f"{len(duplicates)} duplicates, "
        f"{inv_covered_count}/{inv_total} invariants covered"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
