#!/usr/bin/env python3
# Generated by tutor-handouts. Self-consistency scan: the rule files must
# not themselves use the fluff phrases they ban, EXCEPT inside enumerations
# of banned phrases.
#
# A line is filtered (allowed to contain banned tokens) iff it matches ANY of:
#   - contains the literal "Banned:" (case-insensitive)
#   - is a bulleted/numbered list item whose content is a quoted phrase or
#     code-spanned token (e.g.,   - "various"  or  `several`)
#   - is part of CHS-1's enumeration in quality-checklist.md
#
# Anything else with a banned token is a violation.
#
# Usage: check-banned-phrases.py <file-or-dir> [<file-or-dir>...]
# Exit 0 = OK, 1 = violations

from __future__ import annotations

import re
import sys
from pathlib import Path

BANNED = [
    r"\bvarious\b",
    r"\bseveral\b",
    r"\bmany\b",
    r"\bsome\b",
    r"\bmay or may not\b",
    r"\bIn today\b",
]
BANNED_RE = re.compile("|".join(BANNED), re.IGNORECASE)

ALLOWLIST_RE = re.compile(
    r"banned:"                                            # Banned: ...
    r"|^\s*[-*+]\s+[`\"][^`\"]+[`\"]"                      # - "word" / - `word`
    r"|^\s*\d+\.\s+[`\"][^`\"]+[`\"]"                      # 1. "word"
    r"|`[A-Za-z][A-Za-z ' -]+`(\s*,\s*`[A-Za-z][A-Za-z ' -]+`)+",  # enumeration of code-spans
    re.IGNORECASE,
)


def gather_files(paths: list[Path]) -> list[Path]:
    out: list[Path] = []
    for p in paths:
        if p.is_dir():
            out.extend(sorted(p.glob("**/*.md")))
        elif p.is_file():
            out.append(p)
    return out


def main() -> int:
    if len(sys.argv) < 2:
        print("usage: check-banned-phrases.py <file-or-dir> [...]", file=sys.stderr)
        return 2

    paths = [Path(a).resolve() for a in sys.argv[1:]]
    files = gather_files(paths)
    if not files:
        print("error: no files found", file=sys.stderr)
        return 2

    violations: list[str] = []
    for f in files:
        for lineno, line in enumerate(f.read_text().splitlines(), start=1):
            if not BANNED_RE.search(line):
                continue
            if ALLOWLIST_RE.search(line):
                continue
            violations.append(f"{f}:{lineno}: {line.strip()}")

    if violations:
        print("FAIL")
        for v in violations:
            print(f"  - {v}")
        return 1

    print(f"OK: 0 unfiltered hits ({len(files)} files scanned)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
