#!/usr/bin/env python3
# Generated by tutor-handouts. Verifies that every \`{skill-name}\` reference
# in the paired SKILL.md files resolves to an existing skills/{name}/ directory.

from __future__ import annotations

import re
import sys
from pathlib import Path

KNOWN_NON_SKILL_TOKENS = {
    "lstinline", "lstlisting", "documentclass", "code", "fancyhdr", "listings",
    "minted", "booktabs", "lmodern", "amsmath", "amsthm", "hyperref", "geometry",
    "tabularx", "enumitem", "xcolor", "microtype", "environ", "tcb", "ChallengeBase",
    "Challenge", "task_id", "task", "AskUserQuestion", "Glob", "Read", "Bash",
}


def main() -> int:
    repo_root = Path(__file__).resolve().parents[4]
    targets = [
        repo_root / "skills" / "cuda-tutor-setup" / "SKILL.md",
        repo_root / "skills" / "triton-tutor-setup" / "SKILL.md",
        repo_root / "skills" / "tutor-handouts" / "SKILL.md",
    ]

    missing = [str(p) for p in targets if not p.exists()]
    if missing:
        print(f"FAIL: target files missing: {missing}")
        return 1

    skills_dir = repo_root / "skills"
    existing_skills = {p.name for p in skills_dir.iterdir() if p.is_dir()}

    broken: list[str] = []
    total_refs = 0
    for fpath in targets:
        text = fpath.read_text()
        # Skill references look like: `skill-name` — backtick-quoted kebab-case
        for m in re.finditer(r"`([a-z][a-z0-9-]+)`", text):
            token = m.group(1)
            if "-" not in token:
                continue
            if token in KNOWN_NON_SKILL_TOKENS:
                continue
            # Only treat as a skill reference if it looks like a *-tutor[-setup] / tutor-* name
            if not (token.endswith("-tutor") or token.endswith("-tutor-setup") or token.startswith("tutor-")):
                continue
            total_refs += 1
            if token not in existing_skills:
                broken.append(f"{fpath.relative_to(repo_root)}: `{token}` -> skills/{token}/ missing")

    if broken:
        print(f"FAIL: {len(broken)} broken cross-references")
        for b in broken:
            print(f"  - {b}")
        return 1

    print(f"OK: {len(targets)} files scanned, {total_refs} references resolved, 0 broken")
    return 0


if __name__ == "__main__":
    sys.exit(main())
