#!/usr/bin/env bash
# Generated by tutor-handouts. End-to-end dry run for Step 6 of the plan.
#
# Exercises TH2 (bootstrap) and TH8 (build verification) by:
#   1. Copying _common LaTeX assets into a temp Coursepack tree
#   2. Copying _harness Python templates into the temp tree
#   3. Compiling the skill's own smoke-test .tex files using those assets
#   4. Importing challenge_base.py to verify the harness contract holds
#
# This is NOT a full TH3/TH4/TH5 run (those require an LLM to synthesize
# handout content from vault notes). It validates the moving parts that CAN
# be tested mechanically.
#
# Usage:
#   ./dry-run.sh [<temp-dir>]
# Exit 0 = all smoke tests + harness import pass.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_REFS="$(cd "$SCRIPT_DIR/.." && pwd)"
TMP="${1:-$(mktemp -d -t tutor-handouts-dryrun-XXXXXX)}"

echo "=== tutor-handouts dry run ==="
echo "skill refs: $SKILL_REFS"
echo "temp dir:   $TMP"

mkdir -p "$TMP/Coursepack/Handouts/_common"
mkdir -p "$TMP/Coursepack/Exercises/_harness"
cp "$SKILL_REFS"/latex/*.cls "$SKILL_REFS"/latex/commonheader.sty "$TMP/Coursepack/Handouts/_common/"
cp "$SKILL_REFS"/exercise-templates/challenge_base.py "$TMP/Coursepack/Exercises/_harness/"
cp "$SKILL_REFS"/exercise-templates/runner.template.py "$TMP/Coursepack/Exercises/_harness/runner.py"

echo
echo "=== TH2 verification: assets copied ==="
test -f "$TMP/Coursepack/Handouts/_common/handout.cls"     || { echo "FAIL: handout.cls missing"; exit 1; }
test -f "$TMP/Coursepack/Handouts/_common/cheatsheet.cls"  || { echo "FAIL: cheatsheet.cls missing"; exit 1; }
test -f "$TMP/Coursepack/Handouts/_common/problemset.cls"  || { echo "FAIL: problemset.cls missing"; exit 1; }
test -f "$TMP/Coursepack/Handouts/_common/solution.cls"    || { echo "FAIL: solution.cls missing"; exit 1; }
test -f "$TMP/Coursepack/Handouts/_common/commonheader.sty"|| { echo "FAIL: commonheader.sty missing"; exit 1; }
test -f "$TMP/Coursepack/Exercises/_harness/challenge_base.py" || { echo "FAIL: challenge_base.py missing"; exit 1; }
test -f "$TMP/Coursepack/Exercises/_harness/runner.py"     || { echo "FAIL: runner.py missing"; exit 1; }
echo "PASS: 5 LaTeX assets + 2 harness files copied to Coursepack"

echo
echo "=== TH8 verification: PDFs compile ==="
cp "$SKILL_REFS"/latex/smoke-test.tex "$TMP/Coursepack/Handouts/_common/smoke.tex"
cd "$TMP/Coursepack/Handouts/_common"
if command -v latexmk >/dev/null 2>&1; then
    if TEXINPUTS="./:" latexmk -pdf -interaction=nonstopmode -halt-on-error smoke.tex > smoke-build.log 2>&1; then
        size=$(stat -c%s smoke.pdf 2>/dev/null || stat -f%z smoke.pdf 2>/dev/null)
        echo "PASS: smoke.pdf compiled (${size} bytes)"
    else
        echo "FAIL: smoke.pdf did not compile. Last log lines:"
        tail -10 smoke-build.log
        exit 1
    fi
else
    echo "SKIP: latexmk not available; .tex assets were emitted successfully"
fi

echo
echo "=== Harness verification: ChallengeBase importable ==="
cd "$TMP/Coursepack/Exercises/_harness"
if python3 -c "
import sys
sys.path.insert(0, '.')
from challenge_base import ChallengeBase, ChallengeMetadata, TestReport, BenchReport
assert hasattr(ChallengeBase, 'reference_impl')
assert hasattr(ChallengeBase, 'generate_example_test')
assert hasattr(ChallengeBase, 'validate')
assert hasattr(ChallengeBase, 'benchmark')
print('PASS: ChallengeBase contract verified')
"; then
    :
else
    echo "FAIL: ChallengeBase import or contract check failed"
    exit 1
fi

echo
echo "=== Runner verification: discovers no challenges in empty tree ==="
if python3 runner.py "$TMP/Coursepack/Exercises" > runner.log 2>&1; then
    : # runner exits 1 on no challenges; expected
fi
if grep -q "no challenge.py files found" runner.log; then
    echo "PASS: runner.py exited cleanly with no challenges to run"
else
    echo "FAIL: runner.py did not report 'no challenge.py files found':"
    cat runner.log
    exit 1
fi

echo
echo "=== Fixture vault verification ==="
test -d "$SKILL_REFS/test-fixtures/sample-vault/00-Dashboard" || { echo "FAIL: fixture missing"; exit 1; }
test -f "$SKILL_REFS/test-fixtures/sample-vault/00-Dashboard/MOC.md" || { echo "FAIL: MOC.md missing"; exit 1; }
test -d "$SKILL_REFS/test-fixtures/sample-vault/01-CUDA-Kernels/Concepts" || { echo "FAIL: cuda-kernels concepts missing"; exit 1; }
test -d "$SKILL_REFS/test-fixtures/sample-vault/02-CUTLASS/Concepts" || { echo "FAIL: cutlass concepts missing"; exit 1; }
echo "PASS: fixture vault has 2 topics with Concepts/ subdirs"

echo
echo "=== ALL DRY RUN CHECKS PASS ==="
echo "Temp dir kept at: $TMP (delete with: rm -rf $TMP)"
