#!/usr/bin/env python3
# Generated by tutor-handouts. Validates an exercise-bank markdown file.
#
# Asserts:
#   - File parses into ≥1 entries delimited by `### {ID}` headers
#   - Every entry has exactly the 10 required fields in the canonical order
#   - Difficulty is one of {★☆☆, ★★☆, ★★★}
#   - Entry count is exactly 15
#   - IDs are unique and match the file's expected prefix (E-CUDA-NN or E-TRI-NN)
#
# Usage: validate-exercise-bank.py <bank-file.md>
# Exit 0 = OK, 1 = violations

from __future__ import annotations

import re
import sys
from pathlib import Path

REQUIRED_FIELDS = [
    "Topic",
    "Difficulty",
    "Concepts exercised",
    "Prerequisites",
    "Reference",
    "Estimated learner time",
    "Performance target",
    "Test sizes",
    "atol/rtol",
    "FIXME breakdown",
]
VALID_DIFFICULTIES = {"★☆☆", "★★☆", "★★★"}
EXPECTED_ENTRY_COUNT = 15


def main() -> int:
    if len(sys.argv) != 2:
        print("usage: validate-exercise-bank.py <bank-file.md>", file=sys.stderr)
        return 2

    path = Path(sys.argv[1]).resolve()
    if not path.is_file():
        print(f"error: not a file: {path}", file=sys.stderr)
        return 2

    text = path.read_text()
    # Entries delimited by `### {ID} {Title}`
    entry_pattern = re.compile(r"^### (E-[A-Z]+-\d{2}) (.+?)$", re.M)
    matches = list(entry_pattern.finditer(text))
    if not matches:
        print(f"FAIL {path.name}: no `### E-...-NN` entries found")
        return 1

    if "cuda" in path.stem:
        # CUDA stack uses topic-keyed prefixes within the CUDA family
        valid_prefixes = ("E-CUDA-", "E-CUTLASS-", "E-CUTILE-", "E-OGKM-", "E-NCCL-", "E-NVSHMEM-")
    else:
        valid_prefixes = ("E-TRI-",)
    ids = [m.group(1) for m in matches]
    if len(set(ids)) != len(ids):
        dupes = sorted(set(i for i in ids if ids.count(i) > 1))
        print(f"FAIL {path.name}: duplicate IDs: {dupes}")
        return 1
    bad_prefix = [i for i in ids if not any(i.startswith(p) for p in valid_prefixes)]
    if bad_prefix:
        print(f"FAIL {path.name}: IDs not matching valid prefixes {valid_prefixes}: {bad_prefix}")
        return 1
    if len(ids) != EXPECTED_ENTRY_COUNT:
        print(f"FAIL {path.name}: entry count {len(ids)} != {EXPECTED_ENTRY_COUNT}")
        return 1

    violations: list[str] = []
    for i, m in enumerate(matches):
        start = m.end()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        body = text[start:end]
        entry_id = m.group(1)

        found_fields: list[str] = []
        for line in body.splitlines():
            sm = re.match(r"^- ([A-Za-z][\w \-/]+):\s*(.+)$", line)
            if sm:
                field, value = sm.group(1).strip(), sm.group(2).strip()
                found_fields.append(field)
                if field == "Difficulty" and not any(d in value for d in VALID_DIFFICULTIES):
                    violations.append(
                        f"{entry_id}: Difficulty {value!r} not in {sorted(VALID_DIFFICULTIES)}"
                    )

        for req in REQUIRED_FIELDS:
            if req not in found_fields:
                violations.append(f"{entry_id}: missing field {req!r}")

    if violations:
        print(f"FAIL {path.name}: {len(violations)} violations")
        for v in violations:
            print(f"  - {v}")
        return 1

    print(f"OK {path.name}: {len(ids)}/{EXPECTED_ENTRY_COUNT} entries OK, {len(REQUIRED_FIELDS)}/{len(REQUIRED_FIELDS)} fields per entry")
    return 0


if __name__ == "__main__":
    sys.exit(main())
