"""ChallengeBase — abstract autograder base class for tutor-handouts exercises.

Generated by tutor-handouts. Copied verbatim to Coursepack/Exercises/_harness/.

Inspired by AlphaGPU/leetgpu-challenges. Each exercise subclasses ChallengeBase,
provides reference_impl + test-case generators, and runner.py discovers and
executes them.
"""
from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any, Callable

try:
    import torch
except ImportError as e:
    raise ImportError(
        "ChallengeBase requires `torch`. Install with `pip install torch`."
    ) from e


@dataclass
class ChallengeMetadata:
    name: str
    topic: str
    difficulty: str  # "easy" | "medium" | "hard"
    atol: float = 1e-5
    rtol: float = 1e-5
    num_gpus: int = 1
    target_frameworks: list[str] = field(default_factory=lambda: ["cuda", "triton"])


@dataclass
class TestReport:
    challenge_name: str
    framework: str
    cases_total: int
    cases_passed: int
    max_abs_error: float
    failures: list[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return self.cases_passed == self.cases_total


@dataclass
class BenchReport:
    challenge_name: str
    framework: str
    median_ms: float
    iters: int


class ChallengeBase(ABC):
    metadata: ChallengeMetadata

    @abstractmethod
    def reference_impl(self, **kwargs: Any) -> Any:
        ...

    @abstractmethod
    def generate_example_test(self) -> dict[str, Any]:
        ...

    @abstractmethod
    def generate_functional_test(self) -> list[dict[str, Any]]:
        ...

    @abstractmethod
    def generate_performance_test(self) -> dict[str, Any]:
        ...

    def validate(
        self, candidate: Callable[..., Any], framework: str
    ) -> TestReport:
        atol, rtol = self.metadata.atol, self.metadata.rtol
        cases = [self.generate_example_test()] + self.generate_functional_test()
        passed = 0
        max_err = 0.0
        failures: list[str] = []
        for i, case in enumerate(cases):
            kwargs = {k: (v.clone() if isinstance(v, torch.Tensor) else v) for k, v in case.items()}
            ref_kwargs = {k: (v.clone() if isinstance(v, torch.Tensor) else v) for k, v in case.items()}
            expected = self.reference_impl(**ref_kwargs)
            actual = candidate(**kwargs)
            if not isinstance(actual, torch.Tensor) or not isinstance(expected, torch.Tensor):
                failures.append(f"case {i}: non-tensor output type {type(actual).__name__}")
                continue
            err = (actual - expected).abs().max().item()
            max_err = max(max_err, err)
            if torch.allclose(actual, expected, atol=atol, rtol=rtol):
                passed += 1
            else:
                failures.append(f"case {i}: max_abs_err={err:.3e} > atol={atol}")
        return TestReport(
            challenge_name=self.metadata.name,
            framework=framework,
            cases_total=len(cases),
            cases_passed=passed,
            max_abs_error=max_err,
            failures=failures,
        )

    def benchmark(
        self, candidate: Callable[..., Any], framework: str, iters: int = 25, warmup: int = 5
    ) -> BenchReport:
        case = self.generate_performance_test()
        if not torch.cuda.is_available():
            return BenchReport(
                challenge_name=self.metadata.name,
                framework=framework,
                median_ms=float("nan"),
                iters=0,
            )
        for _ in range(warmup):
            candidate(**{k: (v.clone() if isinstance(v, torch.Tensor) else v) for k, v in case.items()})
        torch.cuda.synchronize()
        times: list[float] = []
        for _ in range(iters):
            kwargs = {k: (v.clone() if isinstance(v, torch.Tensor) else v) for k, v in case.items()}
            start = torch.cuda.Event(enable_timing=True)
            end = torch.cuda.Event(enable_timing=True)
            start.record()
            candidate(**kwargs)
            end.record()
            torch.cuda.synchronize()
            times.append(start.elapsed_time(end))
        times.sort()
        median = times[len(times) // 2]
        return BenchReport(
            challenge_name=self.metadata.name,
            framework=framework,
            median_ms=median,
            iters=iters,
        )
