#!/usr/bin/env python3
# Generated by tutor-handouts. Per-exercise autograder spec.
# Fill in the {{...}} markers with values from the exercise-bank entry.

from __future__ import annotations

import torch

from challenge_base import ChallengeBase, ChallengeMetadata


class {{ClassName}}Challenge(ChallengeBase):
    metadata = ChallengeMetadata(
        name="{{Exercise Name}}",
        topic="{{topic-slug}}",
        difficulty="{{easy|medium|hard}}",
        atol={{atol}},
        rtol={{rtol}},
        num_gpus={{num_gpus}},
        target_frameworks={{target_frameworks_list}},
    )

    def reference_impl(self, **kwargs):
        # ECR-7: ≤30 lines, pure torch
        {{REFERENCE_IMPL_BODY}}

    def generate_example_test(self) -> dict:
        return {{EXAMPLE_TEST}}

    def generate_functional_test(self) -> list[dict]:
        return [
            {{FUNCTIONAL_CASE_1}},
            {{FUNCTIONAL_CASE_2}},
            {{FUNCTIONAL_CASE_3}},
            {{FUNCTIONAL_CASE_4}},
        ]

    def generate_performance_test(self) -> dict:
        return {{PERFORMANCE_CASE}}


if __name__ == "__main__":
    c = {{ClassName}}Challenge()
    print(f"{c.metadata.name} [{c.metadata.difficulty}] atol={c.metadata.atol}")
