#!/usr/bin/env python3
# Generated by tutor-handouts. Copied verbatim to Coursepack/Exercises/_harness/runner.py.
#
# Discovers and runs all challenge.py files under a given directory tree.
# Pure-import test by default (no CUDA required).
#
# Usage:
#   python runner.py                                  # all challenges under ../
#   python runner.py 01-cuda-kernels/                 # one topic
#   python runner.py 01-cuda-kernels/02-tiled-matmul/ # one exercise
#   python runner.py --framework triton               # only run Triton starter
#   python runner.py --bench                          # include performance benchmark
#   python runner.py --validate-reference             # validate reference/ against challenge.py::reference_impl

from __future__ import annotations

import argparse
import importlib.util
import sys
from pathlib import Path

HARNESS_DIR = Path(__file__).resolve().parent


def find_challenges(root: Path) -> list[Path]:
    return sorted(root.rglob("challenge.py"))


def import_challenge(path: Path):
    spec = importlib.util.spec_from_file_location(f"challenge_{path.parent.name}", path)
    if spec is None or spec.loader is None:
        raise ImportError(f"cannot load spec for {path}")
    module = importlib.util.module_from_spec(spec)
    sys.path.insert(0, str(HARNESS_DIR))
    try:
        spec.loader.exec_module(module)
    finally:
        sys.path.pop(0)
    return module


def find_challenge_class(module):
    from challenge_base import ChallengeBase  # type: ignore
    for name in dir(module):
        obj = getattr(module, name)
        if isinstance(obj, type) and issubclass(obj, ChallengeBase) and obj is not ChallengeBase:
            return obj
    return None


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="tutor-handouts exercise runner")
    parser.add_argument("path", nargs="?", default=str(HARNESS_DIR.parent), help="dir to scan (default: ../)")
    parser.add_argument("--framework", default="cuda", choices=["cuda", "triton", "pytorch"])
    parser.add_argument("--bench", action="store_true", help="include performance benchmark")
    parser.add_argument("--validate-reference", action="store_true", help="check reference/ vs reference_impl")
    args = parser.parse_args(argv)

    root = Path(args.path).resolve()
    if not root.exists():
        print(f"error: path does not exist: {root}", file=sys.stderr)
        return 2

    challenges = find_challenges(root)
    if not challenges:
        print(f"no challenge.py files found under {root}", file=sys.stderr)
        return 1

    sys.path.insert(0, str(HARNESS_DIR))

    n_imported = 0
    n_failed = 0
    for path in challenges:
        try:
            mod = import_challenge(path)
            cls = find_challenge_class(mod)
            if cls is None:
                print(f"WARN  {path.parent.name}: no Challenge subclass found")
                n_failed += 1
                continue
            instance = cls()
            md = instance.metadata
            print(f"OK    {path.parent.name}: {md.name} [{md.difficulty}] tol={md.atol}/{md.rtol}")
            n_imported += 1
        except Exception as e:
            print(f"FAIL  {path.parent.name}: {type(e).__name__}: {e}")
            n_failed += 1

    print(f"\nimported {n_imported}/{len(challenges)} challenges ({n_failed} failed)")
    return 0 if n_failed == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
