import { existsSync } from "node:fs";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, join } from "node:path";

import { parse } from "jsonc-parser";
import { z } from "zod";

import type { PrdConfig } from "./types.js";

export const PRD_SCHEMA_URL =
  "https://raw.githubusercontent.com/your-org/opencode-pre-read-distillation/main/prd.schema.json";

const LlmConfigSchema = z.object({
  provider: z.enum(["anthropic", "openai-compatible"]).default("anthropic"),
  model: z.string().min(1).default("claude-3-5-haiku-latest"),
  apiKeyEnv: z.string().min(1).default("ANTHROPIC_API_KEY"),
  baseURL: z.string().url().optional(),
  timeoutMs: z.number().int().min(1_000).max(120_000).default(20_000),
  temperature: z.number().min(0).max(1).default(0),
  maxOutputTokens: z.number().int().min(128).max(8_192).default(1_200),
});

const PolicyConfigSchema = z.object({
  policyVersion: z.string().min(1).default("v1"),
  passThroughMaxTokens: z.number().int().min(1).default(1_500),
  passThroughMaxBytes: z.number().int().min(1).default(60_000),
  editIntentPassThroughMaxTokens: z.number().int().min(1).default(3_000),
  distillMinTokens: z.number().int().min(1).default(1_500),
  distillMinBytes: z.number().int().min(1).default(50_000),
  metadataOnlyMinTokens: z.number().int().min(1).default(12_000),
  metadataOnlyMinBytes: z.number().int().min(1).default(450_000),
  maxDistillInputChars: z.number().int().min(4_000).default(120_000),
  generatedPathGlobs: z
    .array(z.string().min(1))
    .default([
      "**/dist/**",
      "**/build/**",
      "**/.next/**",
      "**/coverage/**",
      "**/*.generated.*",
      "**/*-generated.*",
      "**/*.gen.*",
      "**/node_modules/**",
    ]),
  generatedContentMarkers: z
    .array(z.string().min(1))
    .default([
      "@generated",
      "AUTO-GENERATED",
      "DO NOT EDIT",
      "Code generated by",
      "Generated by",
    ]),
  minifiedLineLength: z.number().int().min(80).default(400),
  minifiedLongLineCount: z.number().int().min(1).default(20),
  minifiedNonWhitespaceRatio: z.number().min(0).max(1).default(0.93),
  binaryExtensions: z
    .array(z.string().min(1))
    .default([
      ".png",
      ".jpg",
      ".jpeg",
      ".gif",
      ".webp",
      ".pdf",
      ".zip",
      ".gz",
      ".tar",
      ".exe",
      ".dll",
      ".so",
      ".class",
      ".jar",
      ".woff",
      ".woff2",
      ".ttf",
      ".ico",
      ".mp3",
      ".mp4",
      ".mov",
      ".avi",
    ]),
  documentationExtensions: z
    .array(z.string().min(1))
    .default([".md", ".mdx", ".txt", ".rst", ".adoc"]),
  alwaysPassThroughGlobs: z.array(z.string().min(1)).default([]),
  alwaysMetadataOnlyGlobs: z.array(z.string().min(1)).default([]),
});

const CacheConfigSchema = z.object({
  enabled: z.boolean().default(true),
  ttlSec: z.number().int().min(60).default(86_400),
  maxEntries: z.number().int().min(1).default(2_000),
  maxBytes: z.number().int().min(1_024).default(300_000_000),
  directory: z.string().min(1).optional(),
});

const TelemetryConfigSchema = z.object({
  enabled: z.boolean().default(true),
  directory: z.string().min(1).optional(),
});

const HooksConfigSchema = z.object({
  interceptReadTool: z.boolean().default(true),
  systemPrompt: z.boolean().default(true),
  toolDefinition: z.boolean().default(true),
  chatMessageTracking: z.boolean().default(true),
});

const CustomToolsConfigSchema = z.object({
  distilledRead: z.boolean().default(true),
  rawRead: z.boolean().default(true),
  fileOutline: z.boolean().default(true),
});

const PromptConfigSchema = z.object({
  injectSystemPrompt: z.boolean().default(true),
  appendReadToolDefinition: z.boolean().default(true),
});

const DisplayConfigSchema = z.object({
  operationAnnotations: z.boolean().default(true),
  sessionSummaryBanner: z.boolean().default(true),
  bannerEveryToolResults: z.number().int().min(1).max(200).default(5),
  slashCommands: z.boolean().default(true),
});

export const PrdConfigSchema = z.object({
  $schema: z.string().default(PRD_SCHEMA_URL),
  enabled: z.boolean().default(true),
  debug: z.boolean().default(false),
  llm: LlmConfigSchema,
  policy: PolicyConfigSchema,
  cache: CacheConfigSchema,
  telemetry: TelemetryConfigSchema,
  hooks: HooksConfigSchema,
  customTools: CustomToolsConfigSchema,
  prompt: PromptConfigSchema,
  display: DisplayConfigSchema,
});

type ConfigObject = Record<string, unknown>;

export const DEFAULT_PRD_CONFIG: PrdConfig = {
  $schema: PRD_SCHEMA_URL,
  enabled: true,
  debug: false,
  llm: LlmConfigSchema.parse({}),
  policy: PolicyConfigSchema.parse({}),
  cache: CacheConfigSchema.parse({}),
  telemetry: TelemetryConfigSchema.parse({}),
  hooks: HooksConfigSchema.parse({}),
  customTools: CustomToolsConfigSchema.parse({}),
  prompt: PromptConfigSchema.parse({}),
  display: DisplayConfigSchema.parse({}),
};

function getGlobalConfigDir(): string {
  return process.env.XDG_CONFIG_HOME
    ? join(process.env.XDG_CONFIG_HOME, "opencode")
    : join(homedir(), ".config", "opencode");
}

function getGlobalConfigJsoncPath(): string {
  return join(getGlobalConfigDir(), "prd.jsonc");
}

function getGlobalConfigJsonPath(): string {
  return join(getGlobalConfigDir(), "prd.json");
}

function isObject(value: unknown): value is ConfigObject {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function deepMerge(base: ConfigObject, override: ConfigObject): ConfigObject {
  const merged: ConfigObject = { ...base };

  for (const [key, overrideValue] of Object.entries(override)) {
    const baseValue = merged[key];

    if (isObject(baseValue) && isObject(overrideValue)) {
      merged[key] = deepMerge(baseValue, overrideValue);
      continue;
    }

    merged[key] = overrideValue;
  }

  return merged;
}

function findOpencodeDirectory(startDirectory: string): string | null {
  let current = startDirectory;

  while (current !== "/") {
    const candidate = join(current, ".opencode");
    if (existsSync(candidate)) {
      return candidate;
    }

    const parent = dirname(current);
    if (parent === current) {
      break;
    }

    current = parent;
  }

  return null;
}

function resolveConfigPaths(directory: string): {
  global: string | null;
  configDir: string | null;
  project: string | null;
} {
  let global: string | null = null;
  const globalJsonc = getGlobalConfigJsoncPath();
  const globalJson = getGlobalConfigJsonPath();
  if (existsSync(globalJsonc)) {
    global = globalJsonc;
  } else if (existsSync(globalJson)) {
    global = globalJson;
  }

  let configDir: string | null = null;
  const explicitConfigDir = process.env.OPENCODE_CONFIG_DIR;
  if (explicitConfigDir) {
    const candidateJsonc = join(explicitConfigDir, "prd.jsonc");
    const candidateJson = join(explicitConfigDir, "prd.json");
    if (existsSync(candidateJsonc)) {
      configDir = candidateJsonc;
    } else if (existsSync(candidateJson)) {
      configDir = candidateJson;
    }
  }

  let project: string | null = null;
  const opencodeDir = findOpencodeDirectory(directory);
  if (opencodeDir) {
    const candidateJsonc = join(opencodeDir, "prd.jsonc");
    const candidateJson = join(opencodeDir, "prd.json");
    if (existsSync(candidateJsonc)) {
      project = candidateJsonc;
    } else if (existsSync(candidateJson)) {
      project = candidateJson;
    }
  }

  return {
    global,
    configDir,
    project,
  };
}

async function ensureDefaultGlobalConfigExists(): Promise<void> {
  const globalJsonc = getGlobalConfigJsoncPath();
  const globalJson = getGlobalConfigJsonPath();
  if (existsSync(globalJsonc) || existsSync(globalJson)) {
    return;
  }

  await mkdir(getGlobalConfigDir(), { recursive: true });
  const content = `{
  "$schema": "${PRD_SCHEMA_URL}",
  "display": {
    "operationAnnotations": true,
    "sessionSummaryBanner": true,
    "bannerEveryToolResults": 5,
    "slashCommands": true
  }
}\n`;
  await writeFile(globalJsonc, content, "utf8");
}

async function loadConfigFile(filePath: string): Promise<ConfigObject | null> {
  const raw = await readFile(filePath, "utf8");
  const parsed = parse(raw);
  if (!isObject(parsed)) {
    return null;
  }
  return parsed;
}

function withDefaultStorageDirectories(config: PrdConfig): PrdConfig {
  const baseDataDir = process.env.XDG_DATA_HOME
    ? join(process.env.XDG_DATA_HOME, "opencode", "storage", "plugin", "prd")
    : join(homedir(), ".local", "share", "opencode", "storage", "plugin", "prd");

  const cacheDirectory = config.cache.directory ?? join(baseDataDir, "cache");
  const telemetryDirectory = config.telemetry.directory ?? baseDataDir;

  return {
    ...config,
    cache: {
      ...config.cache,
      directory: cacheDirectory,
    },
    telemetry: {
      ...config.telemetry,
      directory: telemetryDirectory,
    },
  };
}

export async function loadPrdConfig(directory: string): Promise<PrdConfig> {
  await ensureDefaultGlobalConfigExists();

  const paths = resolveConfigPaths(directory);

  let mergedConfig: ConfigObject = { ...DEFAULT_PRD_CONFIG };

  const mergePathOrder = [paths.global, paths.configDir, paths.project];
  for (const configPath of mergePathOrder) {
    if (!configPath) {
      continue;
    }

    try {
      const loaded = await loadConfigFile(configPath);
      if (loaded) {
        mergedConfig = deepMerge(mergedConfig, loaded);
      }
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      throw new Error(`Failed to load PRD config at ${configPath}: ${message}`);
    }
  }

  const parsed = PrdConfigSchema.parse(mergedConfig);
  return withDefaultStorageDirectories(parsed);
}
